name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.3
  pdf: ^3.11.3
  printing: ^5.15.0
  qr_flutter: ^4.1.0
  razorpay_flutter: ^1.4.5
  supabase_flutter: ^2.16.0
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.2
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
