-- Scoped menu management for restaurants and food-court stalls.

create type public.menu_option_group_type as enum ('variant', 'add_on');

create table public.menu_categories (
  id uuid primary key default extensions.gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade,
  stall_id uuid, name text not null check (char_length(trim(name)) between 1 and 120), sort_order integer not null default 0,
  archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  foreign key (stall_id,business_id) references public.stalls(id,business_id) on delete cascade, unique(id,business_id,stall_id)
);
create table public.menu_items (
  id uuid primary key default extensions.gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete cascade,
  stall_id uuid, category_id uuid not null, name text not null check (char_length(trim(name)) between 1 and 160), description text,
  price numeric(12,2) not null check(price>=0), image_path text, is_available boolean not null default true, sort_order integer not null default 0,
  archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  foreign key(category_id) references public.menu_categories(id) on delete restrict,
  foreign key(stall_id,business_id) references public.stalls(id,business_id) on delete cascade
);
create table public.menu_option_groups (
  id uuid primary key default extensions.gen_random_uuid(), menu_item_id uuid not null references public.menu_items(id) on delete cascade,
  name text not null check(char_length(trim(name)) between 1 and 120), type public.menu_option_group_type not null,
  min_select integer not null default 0 check(min_select>=0), max_select integer not null default 1 check(max_select>=1 and max_select>=min_select),
  sort_order integer not null default 0, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.menu_options (
  id uuid primary key default extensions.gen_random_uuid(), option_group_id uuid not null references public.menu_option_groups(id) on delete cascade,
  name text not null check(char_length(trim(name)) between 1 and 120), price_delta numeric(12,2) not null default 0,
  is_available boolean not null default true, sort_order integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index menu_categories_scope_idx on public.menu_categories(business_id,stall_id,sort_order) where archived_at is null;
create index menu_items_scope_idx on public.menu_items(business_id,stall_id,category_id,sort_order) where archived_at is null;

create function private.enforce_menu_scope() returns trigger language plpgsql set search_path='' as $$
declare v_type public.business_type; declare v_category public.menu_categories;
begin
  select type into v_type from public.businesses where id=new.business_id;
  if not found then raise exception 'Business does not exist'; end if;
  if (v_type='restaurant' and new.stall_id is not null) or (v_type='food_court' and new.stall_id is null) then raise exception 'Menu scope does not match business type'; end if;
  if tg_table_name='menu_items' then
    select * into v_category from public.menu_categories where id=new.category_id and archived_at is null;
    if not found or v_category.business_id<>new.business_id or v_category.stall_id is distinct from new.stall_id then raise exception 'Category and item scope must match'; end if;
  end if; return new;
end; $$;
create trigger menu_categories_scope before insert or update on public.menu_categories for each row execute procedure private.enforce_menu_scope();
create trigger menu_items_scope before insert or update on public.menu_items for each row execute procedure private.enforce_menu_scope();
create trigger menu_categories_updated before update on public.menu_categories for each row execute procedure private.set_updated_at();
create trigger menu_items_updated before update on public.menu_items for each row execute procedure private.set_updated_at();
create trigger menu_groups_updated before update on public.menu_option_groups for each row execute procedure private.set_updated_at();
create trigger menu_options_updated before update on public.menu_options for each row execute procedure private.set_updated_at();

create function private.can_manage_menu(p_business_id uuid,p_stall_id uuid) returns boolean language sql stable security definer set search_path='' as $$
 select private.is_business_owner(p_business_id) or exists(select 1 from public.business_memberships where business_id=p_business_id and user_id=(select auth.uid()) and role='manager' and status='active' and p_stall_id is null)
 or exists(select 1 from public.stall_memberships where business_id=p_business_id and stall_id=p_stall_id and user_id=(select auth.uid()) and role='manager' and status='active'); $$;
create function private.can_set_menu_availability(p_business_id uuid,p_stall_id uuid) returns boolean language sql stable security definer set search_path='' as $$
 select private.can_manage_menu(p_business_id,p_stall_id) or exists(select 1 from public.business_memberships where business_id=p_business_id and user_id=(select auth.uid()) and role='kitchen' and status='active' and p_stall_id is null)
 or exists(select 1 from public.stall_memberships where business_id=p_business_id and stall_id=p_stall_id and user_id=(select auth.uid()) and role='kitchen' and status='active'); $$;

alter table public.menu_categories enable row level security; alter table public.menu_items enable row level security; alter table public.menu_option_groups enable row level security; alter table public.menu_options enable row level security;
create policy menu_categories_read on public.menu_categories for select to authenticated using(private.has_business_access(business_id) and (stall_id is null or private.has_stall_access(stall_id)));
create policy menu_items_read on public.menu_items for select to authenticated using(private.has_business_access(business_id) and (stall_id is null or private.has_stall_access(stall_id)));
create policy menu_groups_read on public.menu_option_groups for select to authenticated using(exists(select 1 from public.menu_items i where i.id=menu_item_id and private.has_business_access(i.business_id) and (i.stall_id is null or private.has_stall_access(i.stall_id))));
create policy menu_options_read on public.menu_options for select to authenticated using(exists(select 1 from public.menu_option_groups g join public.menu_items i on i.id=g.menu_item_id where g.id=option_group_id and private.has_business_access(i.business_id) and (i.stall_id is null or private.has_stall_access(i.stall_id))));
grant select on public.menu_categories,public.menu_items,public.menu_option_groups,public.menu_options to authenticated;

create function public.create_menu_category(p_business_id uuid,p_stall_id uuid,p_name text,p_sort_order integer default 0) returns public.menu_categories language plpgsql security definer set search_path='' as $$ declare v public.menu_categories; begin if not private.can_manage_menu(p_business_id,p_stall_id) then raise exception 'Menu management requires owner or manager access';end if;insert into public.menu_categories(business_id,stall_id,name,sort_order) values(p_business_id,p_stall_id,trim(p_name),p_sort_order) returning * into v;return v;end;$$;
create function public.update_menu_category(p_category_id uuid,p_name text,p_sort_order integer) returns public.menu_categories language plpgsql security definer set search_path='' as $$ declare v public.menu_categories;begin select * into v from public.menu_categories where id=p_category_id and archived_at is null;if not found or not private.can_manage_menu(v.business_id,v.stall_id) then raise exception 'Menu management requires owner or manager access';end if;update public.menu_categories set name=trim(p_name),sort_order=p_sort_order where id=p_category_id returning * into v;return v;end;$$;
create function public.archive_menu_category(p_category_id uuid) returns public.menu_categories language plpgsql security definer set search_path='' as $$ declare v public.menu_categories;begin select * into v from public.menu_categories where id=p_category_id and archived_at is null;if not found or not private.can_manage_menu(v.business_id,v.stall_id) then raise exception 'Menu management requires owner or manager access';end if;update public.menu_categories set archived_at=now() where id=p_category_id returning * into v;update public.menu_items set archived_at=now() where category_id=p_category_id and archived_at is null;return v;end;$$;
create function public.create_menu_item(p_business_id uuid,p_stall_id uuid,p_category_id uuid,p_name text,p_description text,p_price numeric,p_image_path text,p_sort_order integer default 0) returns public.menu_items language plpgsql security definer set search_path='' as $$ declare v public.menu_items;begin if not private.can_manage_menu(p_business_id,p_stall_id) then raise exception 'Menu management requires owner or manager access';end if;insert into public.menu_items(business_id,stall_id,category_id,name,description,price,image_path,sort_order) values(p_business_id,p_stall_id,p_category_id,trim(p_name),nullif(trim(p_description),''),p_price,nullif(trim(p_image_path),''),p_sort_order) returning * into v;return v;end;$$;
create function public.update_menu_item(p_item_id uuid,p_category_id uuid,p_name text,p_description text,p_price numeric,p_image_path text,p_sort_order integer) returns public.menu_items language plpgsql security definer set search_path='' as $$ declare v public.menu_items;begin select * into v from public.menu_items where id=p_item_id and archived_at is null;if not found or not private.can_manage_menu(v.business_id,v.stall_id) then raise exception 'Menu management requires owner or manager access';end if;update public.menu_items set category_id=p_category_id,name=trim(p_name),description=nullif(trim(p_description),''),price=p_price,image_path=nullif(trim(p_image_path),''),sort_order=p_sort_order where id=p_item_id returning * into v;return v;end;$$;
create function public.archive_menu_item(p_item_id uuid) returns public.menu_items language plpgsql security definer set search_path='' as $$ declare v public.menu_items;begin select * into v from public.menu_items where id=p_item_id and archived_at is null;if not found or not private.can_manage_menu(v.business_id,v.stall_id) then raise exception 'Menu management requires owner or manager access';end if;update public.menu_items set archived_at=now(),is_available=false where id=p_item_id returning * into v;update public.menu_option_groups set archived_at=now() where menu_item_id=p_item_id and archived_at is null;return v;end;$$;
create function public.set_menu_item_availability(p_item_id uuid,p_is_available boolean) returns public.menu_items language plpgsql security definer set search_path='' as $$ declare v public.menu_items;begin select * into v from public.menu_items where id=p_item_id and archived_at is null;if not found or not private.can_set_menu_availability(v.business_id,v.stall_id) then raise exception 'Availability requires owner, manager, or kitchen access';end if;update public.menu_items set is_available=p_is_available where id=p_item_id returning * into v;return v;end;$$;
create function public.create_menu_option_group(p_item_id uuid,p_name text,p_type public.menu_option_group_type,p_min_select integer,p_max_select integer,p_sort_order integer default 0) returns public.menu_option_groups language plpgsql security definer set search_path='' as $$ declare i public.menu_items;declare v public.menu_option_groups;begin select * into i from public.menu_items where id=p_item_id and archived_at is null;if not found or not private.can_manage_menu(i.business_id,i.stall_id) then raise exception 'Menu management requires owner or manager access';end if;insert into public.menu_option_groups(menu_item_id,name,type,min_select,max_select,sort_order)values(p_item_id,trim(p_name),p_type,p_min_select,p_max_select,p_sort_order)returning * into v;return v;end;$$;
create function public.update_menu_option_group(p_group_id uuid,p_name text,p_min_select integer,p_max_select integer,p_sort_order integer) returns public.menu_option_groups language plpgsql security definer set search_path='' as $$ declare i public.menu_items;declare v public.menu_option_groups;begin select i.* into i from public.menu_option_groups g join public.menu_items i on i.id=g.menu_item_id where g.id=p_group_id and g.archived_at is null;if not found or not private.can_manage_menu(i.business_id,i.stall_id) then raise exception 'Menu management requires owner or manager access';end if;update public.menu_option_groups set name=trim(p_name),min_select=p_min_select,max_select=p_max_select,sort_order=p_sort_order where id=p_group_id returning * into v;return v;end;$$;
create function public.archive_menu_option_group(p_group_id uuid) returns public.menu_option_groups language plpgsql security definer set search_path='' as $$ declare i public.menu_items;declare v public.menu_option_groups;begin select i.* into i from public.menu_option_groups g join public.menu_items i on i.id=g.menu_item_id where g.id=p_group_id and g.archived_at is null;if not found or not private.can_manage_menu(i.business_id,i.stall_id) then raise exception 'Menu management requires owner or manager access';end if;update public.menu_option_groups set archived_at=now() where id=p_group_id returning * into v;return v;end;$$;
create function public.create_menu_option(p_group_id uuid,p_name text,p_price_delta numeric,p_sort_order integer default 0) returns public.menu_options language plpgsql security definer set search_path='' as $$ declare i public.menu_items;declare v public.menu_options;begin select i.* into i from public.menu_option_groups g join public.menu_items i on i.id=g.menu_item_id where g.id=p_group_id and g.archived_at is null;if not found or not private.can_manage_menu(i.business_id,i.stall_id) then raise exception 'Menu management requires owner or manager access';end if;insert into public.menu_options(option_group_id,name,price_delta,sort_order)values(p_group_id,trim(p_name),p_price_delta,p_sort_order)returning * into v;return v;end;$$;
create function public.update_menu_option(p_option_id uuid,p_name text,p_price_delta numeric,p_is_available boolean,p_sort_order integer) returns public.menu_options language plpgsql security definer set search_path='' as $$ declare i public.menu_items;declare v public.menu_options;begin select i.* into i from public.menu_options o join public.menu_option_groups g on g.id=o.option_group_id join public.menu_items i on i.id=g.menu_item_id where o.id=p_option_id;if not found or not private.can_manage_menu(i.business_id,i.stall_id) then raise exception 'Menu management requires owner or manager access';end if;update public.menu_options set name=trim(p_name),price_delta=p_price_delta,is_available=p_is_available,sort_order=p_sort_order where id=p_option_id returning * into v;return v;end;$$;
create function public.delete_menu_option(p_option_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare i public.menu_items;begin select i.* into i from public.menu_options o join public.menu_option_groups g on g.id=o.option_group_id join public.menu_items i on i.id=g.menu_item_id where o.id=p_option_id;if not found or not private.can_manage_menu(i.business_id,i.stall_id) then raise exception 'Menu management requires owner or manager access';end if;delete from public.menu_options where id=p_option_id;end;$$;

revoke all on all functions in schema public from public,anon;
grant execute on function public.create_menu_category(uuid,uuid,text,integer),public.update_menu_category(uuid,text,integer),public.archive_menu_category(uuid),public.create_menu_item(uuid,uuid,uuid,text,text,numeric,text,integer),public.update_menu_item(uuid,uuid,text,text,numeric,text,integer),public.archive_menu_item(uuid),public.set_menu_item_availability(uuid,boolean),public.create_menu_option_group(uuid,text,public.menu_option_group_type,integer,integer,integer),public.update_menu_option_group(uuid,text,integer,integer,integer),public.archive_menu_option_group(uuid),public.create_menu_option(uuid,text,numeric,integer),public.update_menu_option(uuid,text,numeric,boolean,integer),public.delete_menu_option(uuid) to authenticated;
